### ISSUE TITLE
[FreeBSD 13] zkg install zeek-pcapovertcp-plugin - package build_command failed

### ISSUE THREAD

**Issue by lrvl** [emnahum/zeek-pcapovertcp-plugin#3]
- OS FreeBSD 13.2-RELEASE-p3 ( with cmake-3.26.1 installed )
- Package = zeek-5.0.9                     System for detecting network intruders in real-time
- Problem = package build_command failed, logs included

<pre>
# pkg install -y zeek
# zkg search pcap
zeek/emnahum/zeek-pcapovertcp-plugin - Provides PCAP over TCP support for Zeek.

# zkg install zeek-pcapovertcp-plugin
The following packages will be INSTALLED:
  zeek/emnahum/zeek-pcapovertcp-plugin (v1.0.11)

Proceed? [Y/n] y
Installing "zeek/emnahum/zeek-pcapovertcp-plugin"....
Failed installing "zeek/emnahum/zeek-pcapovertcp-plugin": package build_command failed, see log in /root/.zkg/logs/zeek-pcapovertcp-plugin-build.log
error: incomplete installation, the follow packages failed to be installed:
  zeek/emnahum/zeek-pcapovertcp-plugin (v1.0.11)
</pre>

Output of the plugin-build.log

<pre>
In file included from /root/.zkg/clones/package/zeek-pcapovertcp-plugin/src/Plugin.cc:3:
/root/.zkg/clones/package/zeek-pcapovertcp-plugin/src/PcapOverTcp.h:15:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>          // ifreq
         ^~~~~~~~~~~~
1 error generated.
=== STDOUT ===
Build Directory         : build
Zeek Source Directory   :
-- The C compiler identification is Clang 14.0.5
-- The CXX compiler identification is Clang 14.0.5

</pre>

**Comment by emnahum** [comment]
This looks like a building on BSD problem.  There was some leftover include files that it didn't need from the AF_PACKET that the package was based on.  It seems fine to delete them, but I can't test on your specific system (BSD based).   Can you give the latest (v1.0.12) a try?

**Comment by lrvl** [comment]
Install seems to work:

<pre>
[root@beast /usr/local/bin]# zkg --verbose install zeek-pcapovertcp-plugin
The following packages will be INSTALLED:
  zeek/emnahum/zeek-pcapovertcp-plugin (v1.0.12)

Proceed? [Y/n] y
Installing "zeek/emnahum/zeek-pcapovertcp-plugin"...........
Installed "zeek/emnahum/zeek-pcapovertcp-plugin" (v1.0.12)
Loaded "zeek/emnahum/zeek-pcapovertcp-plugin"
[root@beast /usr/local/bin]# zkg info zeek-pcapovertcp-plugin
"zeek/emnahum/zeek-pcapovertcp-plugin" info:
	url: https://github.com/emnahum/zeek-pcapovertcp-plugin
	versions: ['v1.0.0', 'v1.0.1', 'v1.0.2', 'v1.0.3', 'v1.0.4', 'v1.0.5', 'v1.0.6', 'v1.0.7', 'v1.0.8', 'v1.0.9', 'v1.0.10', 'v1.0.11', 'v1.0.12']
	install status:
		current_hash = ce1d2848d58a55d933cac3ce0816efee301a707f
		current_version = v1.0.12
		is_loaded = True
		is_outdated = False
		is_pinned = False
		tracking_method = version
	metadata file: /root/.zkg/clones/package/zeek-pcapovertcp-plugin/zkg.meta
	metadata (from version "v1.0.12"):
		build_command = ./configure && make
		credits = Erich Nahum <github@nahum.org>
		depends = 
			zkg >=2.0
			zeek >=4.0.0
		description = Provides PCAP over TCP support for Zeek.
		plugin_dir = build/Zeek_PcapOverTcp.tgz
		script_dir = scripts
		summary = Provides PCAP over TCP support for Zeek.
		tags = zeek plugin, zeekctl plugin, packet source, pcapovertcp, pcap
</pre>

However I'm doing something wrong I guess:

<pre>
[root@beast /usr/local/bin]# zeek -i pcapovertcp::192.168.3.2:57012 local
fatal error: type of packet source 'pcapovertcp' not recognized, or mode not supported
</pre>

(192.168.3.2 is waiting to provide tcpdump over netcat)

**UPDATE**: After adding this env it works. Is this normally required?

<pre>
# export ZEEK_PLUGIN_PATH="/root/.zkg/plugin_dir/packages/zeek-pcapovertcp-plugin"
</pre>

**Comment by emnahum** [comment]
No, it's not required.  I don't have that defined in my environment.  I'll think about it?

**Comment by emnahum** [comment]
Nothing is coming to mind so I am closing the issue.
